# Generated by Django 6.0.2 on 2026-03-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productvariation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('material', 'material')], max_length=100),
        ),
    ]
