# Generated by Django 6.0.2 on 2026-03-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variation'),
        ('store', '0003_alter_productvariation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variation',
            field=models.ManyToManyField(blank=True, to='store.productvariation'),
        ),
    ]
