# Generated by Django 6.0.2 on 2026-04-03 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('jazzcash', 'JazzCash'), ('debit_card', 'Bank debit card')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('jazzcash_phone', models.CharField(blank=True, max_length=20)),
                ('card_last_four', models.CharField(blank=True, max_length=4)),
                ('cardholder_name', models.CharField(blank=True, max_length=120)),
                ('card_exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('card_exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
